install.packages("dplyr")
library(dplyr)
install.packages("ggplot2")
library(ggplot2)
test <- mpg %>% select(class, cty)
head(test)

df_suv <- df %>% filter(class == "suv")
df_compact <- df %>% filter(class == "compact")
mean(df_suv$cty)
mean(df_compact$cty)